[package]
name = "black-jack"
version = "0.0.15-a2"
authors = ["Miles Granger <miles59923@gmail.com>"]
description = "Rust backend engine for Python package lumber-jack"
repository = "https://github.com/milesgranger/black-jack"
readme = "README.md"
license-file = "LICENSE"

[badges]
travis-ci = { repository = "https://github.com/milesgranger/black-jack", branch = "master" }
coveralls = { repository = "https://github.com/milesgranger/black-jack", branch = "master", service = "github" }

[lib]
name = "blackjack"

[dependencies]
num = "^0.2"
csv = "^1.0.1"

[dev-dependencies]
float-cmp = "0.4.0"
criterion = "0.2"

[[bench]]
name = "bench_marks"
harness = false